{
 "title": "Host Metrics (Zabbix)",
 "tags": [ "host_metrics" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "env", "label": "Env", "query": "{*}" },
   { "name": "group", "label": "Group", "query": "{*}" },
   { "name": "host", "query": "{$env: $group}{*}" },
   {
    "name": "fs",
    "label": "FS filter",
    "query": {}
   },
   { "name": "interval", "label": "Interval", "query": "1m,5m,15m,1h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Aggregate info for selected hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "RAM (Total)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "$$hashKey": "object:157",
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "1h",
        "avg"
       ],
       "text": "groupBy(1h, avg)"
      },
      {
       "$$hashKey": "object:158",
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "1h",
        "sum"
       ],
       "text": "aggregateBy(1h, sum)"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU cores (Total)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "$$hashKey": "object:218",
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "1h",
        "avg"
       ],
       "text": "groupBy(1h, avg)"
      },
      {
       "$$hashKey": "object:219",
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "1h",
        "sum"
       ],
       "text": "aggregateBy(1h, sum)"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/CPU count$/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SWAP (Total)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "$$hashKey": "object:282",
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "1h",
        "avg"
       ],
       "text": "groupBy(1h, avg)"
      },
      {
       "$$hashKey": "object:283",
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "1h",
        "sum"
       ],
       "text": "aggregateBy(1h, sum)"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total swap space" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Usage (AVG)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "$$hashKey": "object:65",
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5m",
        "avg"
       ],
       "text": "groupBy(5m, avg)"
      },
      {
       "$$hashKey": "object:66",
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5m",
        "avg"
       ],
       "text": "aggregateBy(5m, avg)"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU usage" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RAM available (AVG)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "$$hashKey": "object:94",
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "1h",
        "avg"
       ],
       "text": "groupBy(1h, avg)"
      },
      {
       "$$hashKey": "object:95",
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "1h",
        "avg"
       ],
       "text": "aggregateBy(1h, avg)"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/^Memory available in %|Free memory \\(%\\)$/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "host" },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU cores (Total)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU count" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SWAP (Total)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total swap space" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "$$hashKey": "object:150",
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5m",
        "avg"
       ],
       "text": "groupBy(5m, avg)"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU usage" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RAM available",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/^Memory available in %|Free memory \\(%\\)$/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Basic metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Utilization, %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Trends",
        "defaultParams": [ "avg" ],
        "name": "trendValue",
        "params": [
         {
          "name": "type",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "max" ],
       "text": "trendValue(max)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/:.+$/",
        " "
       ],
       "text": "replaceAlias(/:.+$/,  )"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU usage" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory available, %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/: .*$/",
        " "
       ],
       "text": "replaceAlias(/: .*$/,  )"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/^Memory available in %|Free memory \\(%\\)$/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU iowait time, %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/:.+$/",
        " "
       ],
       "text": "replaceAlias(/:.+$/,  )"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU iowait time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Load Average 1 min (total all cores)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Trends",
        "defaultParams": [ "avg" ],
        "name": "trendValue",
        "params": [
         {
          "name": "type",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "max" ],
       "text": "trendValue(max)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/:.+$/",
        " "
       ],
       "text": "replaceAlias(/:.+$/,  )"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Processor load (1 min average per core)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization, %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "CPU" },
       "functions": [
        {
         "def": {
          "category": "Trends",
          "defaultParams": [ "avg" ],
          "name": "trendValue",
          "params": [
           {
            "name": "type",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count"
            ],
            "type": "string"
           }
          ]
         },
         "params": [ "max" ],
         "text": "trendValue(max)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/^CPU (nice|steal|idle|system|user|iowait) time/"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Memory available, bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Available memory" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Number of processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "Processes" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.*/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "OS settings",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "OS" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Maximum number of opened files" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "OS" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Maximum number of processes" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "File Systems capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Disk Space, %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "Filesystems" },
       "functions": [
        {
         "$$hashKey": "object:405",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/ %|\\(percentage\\)/",
          " "
         ],
         "text": "replaceAlias(/ %|\\(percentage\\)/,  )"
        },
        {
         "$$hashKey": "object:406",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Filesystem: Free disk space.*on|Free disk space on/",
          " "
         ],
         "text": "replaceAlias(/Filesystem: Free disk space.*on|Free disk space on/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/^Free disk space on $fs \\(percentage\\)$/"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Free Disk Space, bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "$$hashKey": "object:243",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Free disk space on /",
          " "
         ],
         "text": "replaceAlias(/Free disk space on /,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/^Free disk space on ${fs}$/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Disk size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "Filesystems" },
       "functions": [
        {
         "$$hashKey": "object:298",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/ %|\\(percentage\\)/",
          " "
         ],
         "text": "replaceAlias(/ %|\\(percentage\\)/,  )"
        },
        {
         "$$hashKey": "object:299",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Filesystem: Free disk space.*on|Free disk space on/",
          " "
         ],
         "text": "replaceAlias(/Filesystem: Free disk space.*on|Free disk space on/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/^Total disk space on $fs$/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Free Inodes (percentage)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "Filesystems" },
       "functions": [
        {
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/^(.*)Free inodes on (\\S+) .*$/",
          "$1$2"
         ],
         "text": "replaceAlias(/^(.*)Free inodes on (\\S+) .*$/, $1$2)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/^Free inodes on ${fs} \\(percentage\\)$/"
       },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Write:Ops per second/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Write Bytes/sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "Disk Performance" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Write:Bytes.sec/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Write Latency (all ops)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Write:ms/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "application": { "filter": "Disk Performance" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Read:Ops per second/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Read Bytes/sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Read:Bytes.sec/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Read Latency (all ops)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "application": { "filter": "Disk Performance" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Read:ms/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network IN",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Incoming network traffic on /",
          " "
         ],
         "text": "replaceAlias(/Incoming network traffic on /,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Incoming network traffic on/" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Network OUT",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Outgoing network traffic on /",
          " "
         ],
         "text": "replaceAlias(/Outgoing network traffic on /,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Outgoing network traffic on/" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Network IN dropped and errors pps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "$$hashKey": "object:175",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Incoming network traffic/",
          " "
         ],
         "text": "replaceAlias(/Incoming network traffic/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Incoming dropped pps/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "$$hashKey": "object:196",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Incoming network traffic/",
          " "
         ],
         "text": "replaceAlias(/Incoming network traffic/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Incoming errors pps/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Network OUT dropped and errors pps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "$$hashKey": "object:233",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Outgoing network traffic/",
          " "
         ],
         "text": "replaceAlias(/Outgoing network traffic/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Outgoing errors pps on/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "$$hashKey": "object:254",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Outgoing network traffic/",
          " "
         ],
         "text": "replaceAlias(/Outgoing network traffic/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Outgoing dropped pps on/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Arp cache count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "$$hashKey": "object:231",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Incoming network traffic/",
          " "
         ],
         "text": "replaceAlias(/Incoming network traffic/,  )"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/^Arp cache count for/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Network interfaces" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/^neigh.default.gc_thresh/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "nf conntrack",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "nf.conntrack.count" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "$$hashKey": "object:382",
         "def": {
          "category": "Transform",
          "defaultParams": [
           0
          ],
          "name": "removeBelowValue",
          "params": [
           { "name": "number", "type": "float" }
          ]
         },
         "params": [ "1" ],
         "text": "removeBelowValue(1)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "nf.conntrack.limit" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Swap %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Free swap space in %" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Sockets statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open sockets by type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "Network" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/^TCP sockets in/" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application logs [$interval]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{host}}/{{type}}/{{severity}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1084",
         "fake": true,
         "field": "host",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1085",
         "fake": true,
         "field": "severity",
         "id": "5",
         "settings": {
          "min_doc_count": 1,
          "missing": "?",
          "order": "desc",
          "orderBy": "_term",
          "size": "10"
         },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1086",
         "fake": true,
         "field": "type",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1087",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:1082", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "host:${host:lucene}",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Application logs",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 37 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "alias": "{{host}}/{{type}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "host",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "type",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "env:$env AND host:${host:lucene}",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Access logs for [$interval]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{host}}/{{type}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:997",
         "fake": true,
         "field": "host",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:998",
         "fake": true,
         "field": "type",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:999",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:995", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "host:${host:lucene}",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Access logs",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 46 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "alias": "{{host}}/{{type}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "host",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "type",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "env:$env AND host:${host:lucene}",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "System logs for [$interval]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{host}}/{{syslog.program}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:743",
         "fake": true,
         "field": "host",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:744",
         "fake": true,
         "field": "syslog.program",
         "id": "3",
         "settings": {
          "min_doc_count": 1,
          "missing": "?",
          "order": "desc",
          "orderBy": "_term",
          "size": "5"
         },
         "type": "terms"
        },
        {
         "$$hashKey": "object:745",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:741", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "host:${host:lucene}",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "System logs",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "alias": "{{host}}/{{syslog.program}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "host",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "syslog.program",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "env:$env AND host:${host:lucene}",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Security logs for [2m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{host}}/{{type}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:830",
         "fake": true,
         "field": "host",
         "id": "4",
         "settings": {
          "min_doc_count": 1,
          "missing": "?",
          "order": "desc",
          "orderBy": "_count",
          "size": "10"
         },
         "type": "terms"
        },
        {
         "$$hashKey": "object:831",
         "fake": true,
         "field": "type",
         "id": "3",
         "settings": {
          "min_doc_count": 1,
          "missing": "?",
          "order": "desc",
          "orderBy": "_count",
          "size": "5"
         },
         "type": "terms"
        },
        {
         "$$hashKey": "object:832",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:828", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "host:${host:lucene}",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Security logs",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 64 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "alias": "{{host}}/{{type}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "host",
         "id": "4",
         "settings": {
          "min_doc_count": 1,
          "missing": "?",
          "order": "desc",
          "orderBy": "_term",
          "size": "10"
         },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "type",
         "id": "3",
         "settings": {
          "min_doc_count": 1,
          "missing": "?",
          "order": "desc",
          "orderBy": "_term",
          "size": "5"
         },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "env:$env AND host:${host:lucene}",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Zabbix agent details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "dtdhms" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "System uptime" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Zabbix agent availability",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "Zabbix agent available" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Zabbix agent certificates expiration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "Zabbix agent" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.+): Zabbix agent: certificate will expire in days for (.+)/",
          "$1: $2"
         ],
         "text": "replaceAlias(/(.+): Zabbix agent: certificate will expire in days for (.+)/, $1: $2)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/Zabbix agent: certificate will expire in days for .*/"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Threatstack agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threatstack agent components status history",
     "type": "graph",
     "description": "0 - Threatstack component is DOWN<br>\n1 - Threatstack component is UP<br>\n2 - Threatstack component is unconfigured",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "component status" }
     ],
     "targets": [
      {
       "application": { "filter": "Threatstack" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.*/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Zabbix alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "type": "alexanderzobnin-zabbix-triggers-panel",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "application": { "filter": "/.*/" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "" },
       "options": {
        "acknowledged": 2,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 0,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default"
       },
       "proxy": { "filter": "" },
       "showProblems": "problems",
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "/.*/" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}