{
 "title": "Patroni overview",
 "tags": [ "Patroni" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Env", "query": "{*}" },
   {
    "name": "group",
    "label": "group",
    "query": {}
   },
   {
    "name": "host",
    "label": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Patroni cluster name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent scope" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Visible cluster members",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni visible cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni db port check failed cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent version" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent role",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent role" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent state" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni monitoring state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni monitoring state" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Visible cluster members",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni visible cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni monitoring script last error",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni monitoring last error" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Patroni cluster name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent scope" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Visible cluster members",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni visible cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni db port check failed cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent version" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent role",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent role" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent state" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni monitoring state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni monitoring state" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Visible cluster members",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni visible cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni monitoring script last error",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni monitoring last error" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Patroni cluster name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent scope" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Visible cluster members",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni visible cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni db port check failed cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent version" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent role",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent role" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent state" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni monitoring state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni monitoring state" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Visible cluster members",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni visible cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni monitoring script last error",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni monitoring last error" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Patroni cluster name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent scope" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Visible cluster members",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni visible cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni db port check failed cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent version" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent role",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent role" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent state" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni monitoring state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni monitoring state" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Visible cluster members",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni visible cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni monitoring script last error",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni monitoring last error" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Patroni cluster name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent scope" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Visible cluster members",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni visible cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni db port check failed cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent version" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent role",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent role" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent state" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni monitoring state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni monitoring state" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Visible cluster members",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni visible cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni monitoring script last error",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni monitoring last error" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Patroni cluster name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent scope" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Visible cluster members",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni visible cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni db port check failed cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent version" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent role",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent role" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni agent state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni agent state" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni monitoring state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni monitoring state" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Visible cluster members",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Patroni visible cluster members"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patroni monitoring script last error",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Patroni" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Patroni monitoring last error" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}