{
 "title": "Mamonsu",
 "description": "Grafana dashboard for Mamonsu",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": {}
   },
   {
    "name": "group",
    "label": "Group",
    "query": {}
   },
   {
    "name": "host",
    "label": "Host",
    "query": {}
   },
   {
    "name": "database",
    "label": "Database",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Database overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zabbix Agent",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Monitoring agent" },
     "functions": [
      {
       "$$hashKey": "object:5650",
       "def": {
        "category": "Special",
        "defaultParams": [ "avg" ],
        "name": "consolidateBy",
        "params": [
         {
          "name": "type",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "min" ],
       "text": "consolidateBy(min)"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Zabbix agent ping" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Mamonsu status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Mamonsu: plugin keep alive" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DB status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PostgreSQL: ping" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Database size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Database $database: size" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PostgreSQL: cache hit ratio" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "WAL count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "PostgreSQL: count of xlog files"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DB uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PostgreSQL: service uptime" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Database server ping (time)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 3 },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "functions": [
      {
       "$$hashKey": "object:7032",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "ping (ms)" ],
       "text": "setAlias(ping (ms))"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PostgreSQL: ping" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Database active connections (count)",
   "type": "graph",
   "description": "PostgreSQL connections (max/total/active/idle/aborted)",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 3 },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "functions": [
      {
       "$$hashKey": "object:7176",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "maximum connections" ],
       "text": "setAlias(maximum connections)"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "PostgreSQL: max connections" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "functions": [
      {
       "$$hashKey": "object:7254",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "used connections" ],
       "text": "setAlias(used connections)"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "PostgreSQL: number of total connections"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Streaming replication lag (time)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 3 },
   "targets": [
    {
     "application": { "filter": "App-PostgresPro-Linux" },
     "functions": [
      {
       "$$hashKey": "object:6901",
       "added": false,
       "def": {
        "category": "Transform",
        "defaultParams": [],
        "name": "rate",
        "params": []
       },
       "params": [],
       "text": "rate()"
      }
     ],
     "group": { "filter": "$env: $group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Delta of total lag for .*/" },
     "itemids": "Ti",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zabbix messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Problems",
     "type": "alexanderzobnin-zabbix-triggers-panel",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 9 },
     "targets": [
      {
       "application": { "filter": "/.*/" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "" },
       "options": {
        "acknowledged": 2,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 0,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default"
       },
       "proxy": { "filter": "" },
       "showProblems": "problems",
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL base metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections max/total/active/idle/aborted",
     "type": "graph",
     "description": "PostgreSQL connections (max/total/active/idle/aborted)",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:7070",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "total" ],
         "text": "setAlias(total)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: number of total connections"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:7091",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "active" ],
         "text": "setAlias(active)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: number of active connections"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:7112",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "idle" ],
         "text": "setAlias(idle)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: number of idle connections"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:7133",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "idle in transcation" ],
         "text": "setAlias(idle in transcation)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: number of idle in transaction connections"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:7154",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "disabled" ],
         "text": "setAlias(disabled)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL: number of disabled" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:7175",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "aborted" ],
         "text": "setAlias(aborted)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: number of idle in transaction (aborted)"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Transactions commited/deadlocks/rollbacks",
     "type": "graph",
     "description": "Transactions: commit rate, deadlocks, rollbacks",
     "gridPos": { "h": 9, "w": 10, "x": 11, "y": 12 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:6117",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "commited" ],
         "text": "setAlias(commited)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL transactions: total" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:6138",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "deadlocks" ],
         "text": "setAlias(deadlocks)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL event: deadlocks" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:6159",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "rollbacked" ],
         "text": "setAlias(rollbacked)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL event: rollbacks" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Tuples deleted/fetched/inserted/returned/updated (ops/sec)",
     "type": "graph",
     "description": "PostgreSQL tuples: deleted, fetched, inserted, returned",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:8495",
         "def": {
          "category": "Transform",
          "defaultParams": [],
          "name": "delta",
          "params": []
         },
         "params": [],
         "text": "delta()"
        },
        {
         "$$hashKey": "object:8496",
         "def": {
          "category": "Aggregate",
          "defaultParams": [
           "1m",
           "avg"
          ],
          "name": "aggregateBy",
          "params": [
           { "name": "interval", "type": "string" },
           {
            "name": "function",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "1m",
          "max"
         ],
         "text": "aggregateBy(1m, max)"
        },
        {
         "$$hashKey": "object:8497",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "deleted" ],
         "text": "setAlias(deleted)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL tuples: deleted" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:8520",
         "def": {
          "category": "Transform",
          "defaultParams": [],
          "name": "rate",
          "params": []
         },
         "params": [],
         "text": "rate()"
        },
        {
         "$$hashKey": "object:8521",
         "def": {
          "category": "Aggregate",
          "defaultParams": [
           "1m",
           "avg"
          ],
          "name": "aggregateBy",
          "params": [
           { "name": "interval", "type": "string" },
           {
            "name": "function",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "1m",
          "max"
         ],
         "text": "aggregateBy(1m, max)"
        },
        {
         "$$hashKey": "object:8522",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "fetched" ],
         "text": "setAlias(fetched)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL tuples: fetched" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:8545",
         "def": {
          "category": "Transform",
          "defaultParams": [],
          "name": "rate",
          "params": []
         },
         "params": [],
         "text": "rate()"
        },
        {
         "$$hashKey": "object:8546",
         "def": {
          "category": "Aggregate",
          "defaultParams": [
           "1m",
           "avg"
          ],
          "name": "aggregateBy",
          "params": [
           { "name": "interval", "type": "string" },
           {
            "name": "function",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "1m",
          "max"
         ],
         "text": "aggregateBy(1m, max)"
        },
        {
         "$$hashKey": "object:8547",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "inserted" ],
         "text": "setAlias(inserted)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL tuples: inserted" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:8570",
         "def": {
          "category": "Transform",
          "defaultParams": [],
          "name": "rate",
          "params": []
         },
         "params": [],
         "text": "rate()"
        },
        {
         "$$hashKey": "object:8571",
         "def": {
          "category": "Aggregate",
          "defaultParams": [
           "1m",
           "avg"
          ],
          "name": "aggregateBy",
          "params": [
           { "name": "interval", "type": "string" },
           {
            "name": "function",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "1m",
          "max"
         ],
         "text": "aggregateBy(1m, max)"
        },
        {
         "$$hashKey": "object:8572",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "returned" ],
         "text": "setAlias(returned)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL tuples: returned" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:8595",
         "def": {
          "category": "Transform",
          "defaultParams": [],
          "name": "rate",
          "params": []
         },
         "params": [],
         "text": "rate()"
        },
        {
         "$$hashKey": "object:8596",
         "def": {
          "category": "Aggregate",
          "defaultParams": [
           "1m",
           "avg"
          ],
          "name": "aggregateBy",
          "params": [
           { "name": "interval", "type": "string" },
           {
            "name": "function",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "1m",
          "max"
         ],
         "text": "aggregateBy(1m, max)"
        },
        {
         "$$hashKey": "object:8597",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "updated" ],
         "text": "setAlias(updated)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL tuples: updated" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Blocks hit/read (bytes)",
     "type": "graph",
     "description": "PostgreSQL blocks hit, read",
     "gridPos": { "h": 10, "w": 10, "x": 11, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:8708",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "hit" ],
         "text": "setAlias(hit)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL blocks: hit" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:8729",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "read" ],
         "text": "setAlias(read)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL blocks: read" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "PostgreSQL statements read/write/cpu io (time)",
     "type": "graph",
     "description": "PostgreSQL statements",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:5130",
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "read" ],
         "text": "setAlias(read)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL statements: read io time"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:5132",
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "write" ],
         "text": "setAlias(write)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL statements: write io time"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:5134",
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "other" ],
         "text": "setAlias(other)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL statements: other (mostly cpu) time"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "PostgreSQL statements read/write/others (bytes)",
     "type": "graph",
     "description": "PostgreSQL connections",
     "gridPos": { "h": 11, "w": 10, "x": 11, "y": 31 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:7434",
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "read" ],
         "text": "setAlias(read)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL statements: read bytes/s"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:7436",
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "write" ],
         "text": "setAlias(write)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL statements: write bytes/s"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:7438",
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "dirty" ],
         "text": "setAlias(dirty)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL statements: dirty bytes/s"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Temp files written (bytes)",
     "type": "graph",
     "description": "PostgreSQL temp files written",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:7474",
         "def": {
          "category": "Transform",
          "defaultParams": [],
          "name": "delta",
          "params": []
         },
         "params": [],
         "text": "delta()"
        },
        {
         "$$hashKey": "object:7567",
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "bytes written" ],
         "text": "setAlias(bytes written)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL temp: bytes written" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Blocks write (count)",
     "type": "graph",
     "description": "PostgreSQL bgwriter: buffers written during checkpoints, buffers written, number of bgwriter stopped by max write count, buffers written directly by a backend, times a backend execute its own fsync, buffers allocated",
     "gridPos": { "h": 10, "w": 10, "x": 11, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:8308",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "buffers written" ],
         "text": "setAlias(buffers written)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL bgwriter: buffers written"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:8329",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "buffers written by backend" ],
         "text": "setAlias(buffers written by backend)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL bgwriter: buffers written directly by a backend"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:8350",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [
          "buffers written during checkpoints"
         ],
         "text": "setAlias(buffers written during checkpoints)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL bgwriter: buffers written during checkpoints"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Checkpoint by wal/timeout (count)",
     "type": "graph",
     "description": "PostgreSQL checkpoint",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:8040",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "checkpoints by wal (in hour)" ],
         "text": "setAlias(checkpoints by wal (in hour))"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL checkpoints: by wal (in hour)"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:8061",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [
          "checkpoints by timeout (in hour)"
         ],
         "text": "setAlias(checkpoints by timeout (in hour))"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL checkpoints: by timeout (in hour)"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "WAL write speed (bytes/sec)",
     "type": "graph",
     "description": "PostgreSQL: wal write speed",
     "gridPos": { "h": 9, "w": 10, "x": 11, "y": 52 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:9037",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "wal write speed" ],
         "text": "setAlias(wal write speed)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL: wal write speed" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Checkpoint write/sync time",
     "type": "graph",
     "description": "PostgreSQL checkpoint",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL checkpoint: write time"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL checkpoint: sync time"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Shared buffers (size, bytes)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 11, "y": 61 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:200",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "shared buffers" ],
         "text": "setAlias(shared buffers)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "PostgreSQL: shared buffer size" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:221",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "shared buffers dirty" ],
         "text": "setAlias(shared buffers dirty)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: shared buffer dirty size"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:242",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "shared buffers twice used" ],
         "text": "setAlias(shared buffers twice used)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: shared buffer twice used size"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Autovacuum workers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:9556",
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "count of autovacuum workers" ],
         "text": "setAlias(count of autovacuum workers)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "PostgreSQL: count of autovacuum workers"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Streaming replication lag (time)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 70 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "functions": [
        {
         "$$hashKey": "object:6725",
         "def": {
          "category": "Transform",
          "defaultParams": [],
          "name": "rate",
          "params": []
         },
         "params": [],
         "text": "rate()"
        },
        {
         "$$hashKey": "object:6726",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Replication lag, sec" ],
         "text": "setAlias(Replication lag, sec)"
        }
       ],
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Delta of total lag for .*/" },
       "itemids": "$env",
       "options": {
        "acknowledged": 2,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 0,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default"
       },
       "proxy": { "filter": "" },
       "showProblems": "problems",
       "slaInterval": "none",
       "slaProperty": { "name": "SLA", "property": "sla" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Relations size (bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "App-PostgresPro-Linux" },
       "group": { "filter": "$env: $group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/^(Relation size: .*)/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}